### ISSUE TITLE
Funnel de registro de empresa

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizneUserApp#1]
## Información rápida
- Funnel de registro de empresa que deseamos agregar eventos de tracking para analiticas

## ¿Qué cambia esto?
- [x] [Tipo de usuario](https://github.com/BizneMX/BizneUserApp/issues/3)
- [x] [Boton de Continuar](https://github.com/BizneMX/BizneUserApp/issues/4)
- [x] [Paso 1: Nombre completo](https://github.com/BizneMX/BizneUserApp/issues/5)
- [x] [Paso 2: Email y contraseña](https://github.com/BizneMX/BizneUserApp/issues/6)
- [x] [Paso 3: Fecha de nacimiento y género](https://github.com/BizneMX/BizneUserApp/issues/7)
- [x] [Paso 4: Perteneces a una organización](https://github.com/BizneMX/BizneUserApp/issues/8)
- [x] [Paso 4: Selección de organización y role](https://github.com/BizneMX/BizneUserApp/issues/9)
- [x] [Permitir ubicación](https://github.com/BizneMX/BizneUserApp/issues/10)
- [x] [Permitir notificaciones](https://github.com/BizneMX/BizneUserApp/issues/11)

## ¿Por qué estás cambiando eso?
- Detectar posibles cuellos de botella durante el proceso de registro(usuario/empresas)
- Adaptar el proceso y así reducir fricciones con el usuario final
- Incrementar el porcentaje de registros completos

## ¿Cómo se prueba?
- Una vez enviados los cambios en el codigo, podremos ver los eventos reflejados dentro de FireBase
