### ISSUE TITLE
Funnel Menu Alimentos

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizneUserApp#23]
## Información rápida
- Funnel del menu de las fondas y restaurantes que deseamos agregar eventos de tracking para analíticas

## ¿Qué cambia esto?
- [ ] [Botón de Fondas](https://github.com/BizneMX/BizneUserApp/issues/12)
- [ ] [Botón de Restaurantes](https://github.com/BizneMX/BizneUserApp/issues/13)
- [ ] [Botón de Agendar](https://github.com/BizneMX/BizneUserApp/issues/14)
- [ ] [Botón de ver menu](https://github.com/BizneMX/BizneUserApp/issues/15)
- [ ] [Botón de come aquí](https://github.com/BizneMX/BizneUserApp/issues/16)
- [ ] [Botón de menu del dia](https://github.com/BizneMX/BizneUserApp/issues/17)
- [ ] [Botón de horarios](https://github.com/BizneMX/BizneUserApp/issues/18)
- [ ] [Botón de WhatsApp](https://github.com/BizneMX/BizneUserApp/issues/19)
- [ ] [Botón de comida del dia](https://github.com/BizneMX/BizneUserApp/issues/20)
- [ ] [Botón de alimentos y bebidas](https://github.com/BizneMX/BizneUserApp/issues/21)
- [ ] [Botón de especialidades y promociones](https://github.com/BizneMX/BizneUserApp/issues/22)

## ¿Por qué estás cambiando eso?
- Detectar la interacción del usuario con las fondas o restaurantes que incluyen un menú
- Detectar la interacción del usuario con las fondas o restaurantes que no incluyen un menú
- Detectar el porcentaje de conversión con las fondas o restaurantes que incluyen un menú
- Detectar el porcentaje de conversión con las fondas o restaurantes que no incluyen un menú

## ¿Cómo se prueba?
- Una vez enviados los cambios en el codigo, podremos ver los eventos reflejados dentro de FireBase
