### ISSUE TITLE
Funnel Mapa

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizneUserApp#31]
## Información rápida
- Funnel del menu de las fondas y restaurantes que deseamos agregar eventos de tracking para analiticas

## ¿Qué cambia esto?
- [ ] [Boton de Mas cercanas](https://github.com/BizneMX/BizneUserApp/issues/24)
- [ ] [Boton de Favoritas](https://github.com/BizneMX/BizneUserApp/issues/25)
- [ ] [Boton de Abiertas](https://github.com/BizneMX/BizneUserApp/issues/26)
- [ ] [Interacción con el mapa](https://github.com/BizneMX/BizneUserApp/issues/27)
- [ ] [Boton de WhatsApp](https://github.com/BizneMX/BizneUserApp/issues/28)
- [ ] [Boton de Telegram](https://github.com/BizneMX/BizneUserApp/issues/29)

## ¿Por qué estás cambiando eso?
- Detectar la proximidad de las fondas o restaurantes con respecto al usuario
- Recabar información de la interacción del usuario con el mapa
- Detectar zonas más concurridas por los usuarios

## ¿Cómo se prueba?
- Una vez enviados los cambios en el codigo, podremos ver los eventos reflejados dentro de FireBase
