### ISSUE TITLE
Funnel Menu Principal

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizneUserApp#36]
## Información rápida
- Funnel de las interacciones en la seccion del usuario que deseamos agregar eventos de tracking para analiticas

## ¿Qué cambia esto?
- [ ] [Boton de Mi Saldo](https://github.com/BizneMX/BizneUserApp/issues/32)
- [ ] [Boton de QR](https://github.com/BizneMX/BizneUserApp/issues/33)
- [ ] [Boton de Alertas](https://github.com/BizneMX/BizneUserApp/issues/34)
- [ ] [Boton de Perfil](https://github.com/BizneMX/BizneUserApp/issues/35)

## ¿Por qué estás cambiando eso?
- Recabar información de la interacción del usuario con el menu principal
- Detectar opciones más usadas por los usuarios

## ¿Cómo se prueba?
- Una vez enviados los cambios en el codigo, podremos ver los eventos reflejados dentro de FireBase
