### ISSUE TITLE
Funnel Perfil

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizneUserApp#43]
## Información rápida
- Funnel de las interacciones del usuario en la sección de perfil que deseamos agregar eventos de tracking para analíticas

## ¿Qué cambia esto?
- [ ] [Botón de Perfil](https://github.com/BizneMX/BizneUserApp/issues/37)
- [ ] [Botón de Historial de Consumo](https://github.com/BizneMX/BizneUserApp/issues/38)
- [ ] [Botón de Historial de Comidas](https://github.com/BizneMX/BizneUserApp/issues/39)
- [ ] [Botón de Mis Reservas](https://github.com/BizneMX/BizneUserApp/issues/40)
- [ ] [Botón de Legal](https://github.com/BizneMX/BizneUserApp/issues/41)
- [ ] [Botón de Ayuda](https://github.com/BizneMX/BizneUserApp/issues/42)

## ¿Por qué estás cambiando eso?
- Recabar información de la interacción del usuario con la sección de perfil
- Detectar las opciones mas usadas por los usuarios

## ¿Cómo se prueba?
- Una vez enviados los cambios en el código, podremos ver los eventos reflejados dentro de FireBase
