### ISSUE TITLE
Funnel Compra

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizneUserApp#53]
## Información rápida
- Funnel de las interacciones del usuario con el proceso de compra que deseamos agregar eventos de tracking para analíticas

## ¿Qué cambia esto?
- [x] [Botón de Continuar](https://github.com/BizneMX/BizneUserApp/issues/44)
- [x] [Botón de Cancelar](https://github.com/BizneMX/BizneUserApp/issues/45)
- [x] [Botón de En la Fonda](https://github.com/BizneMX/BizneUserApp/issues/46)
- [x] [Botón de Para Recoger](https://github.com/BizneMX/BizneUserApp/issues/47)
- [x] [Botón de Regresar](https://github.com/BizneMX/BizneUserApp/issues/48)
- [x] [Botón de Contacta al Negocio](https://github.com/BizneMX/BizneUserApp/issues/49)
- [x] [Botón de Continuar](https://github.com/BizneMX/BizneUserApp/issues/50)
- [x] [Botón de Calificar](https://github.com/BizneMX/BizneUserApp/issues/51)
- [x] [Botón de Saltar](https://github.com/BizneMX/BizneUserApp/issues/52)

## ¿Por qué estás cambiando eso?
- Recabar información de la interacción del usuario con el proceso de compra
- Recabar información de la interacción del usuario con el proceso de calificación del servicio

## ¿Cómo se prueba?
- Una vez enviados los cambios en el código, podremos ver los eventos reflejados dentro de FireBase
