### ISSUE TITLE
Funnel Compra Bzcoins

### ISSUE THREAD

**Issue by jtapia** [BizneMX/BizneUserApp#77]
## Información rápida
- Funnel de las interacciones en la seccion de saldo del usuario que deseamos agregar eventos de tracking para analiticas

## ¿Qué cambia esto?
- [ ] [Botón de Recarga Saldo](https://github.com/BizneMX/BizneUserApp/issues/67)
- [ ] [Botón de Contacto](https://github.com/BizneMX/BizneUserApp/issues/68)
- [ ] [Botón de Paga 500](https://github.com/BizneMX/BizneUserApp/issues/69)
- [ ] [Botón de Paga 300](https://github.com/BizneMX/BizneUserApp/issues/70)
- [ ] [Botón de Paga 100](https://github.com/BizneMX/BizneUserApp/issues/71)
- [ ] [Botón de Continuar](https://github.com/BizneMX/BizneUserApp/issues/72)
- [ ] [Botón de Cancelar](https://github.com/BizneMX/BizneUserApp/issues/73)
- [ ] [Botón de Pagar](https://github.com/BizneMX/BizneUserApp/issues/74)
- [ ] [Botón de Cancelar](https://github.com/BizneMX/BizneUserApp/issues/75)
- [ ] [Vista Confirmación](https://github.com/BizneMX/BizneUserApp/issues/76)

## ¿Por qué estás cambiando eso?
- Recabar información de la interacción del usuario con el proceso de compra de Bzcoins

## ¿Cómo se prueba?
- Una vez enviados los cambios en el codigo, podremos ver los eventos reflejados dentro de FireBase

## Capturas de pantalla (si corresponde)

![IMG_8259](https://github.com/user-attachments/assets/383e34e4-89d1-4933-b74c-0fa20d92622b)

![IMG_8260](https://github.com/user-attachments/assets/9da70b53-d486-4d4a-8780-90752b716f2a)
